DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sales INTEGER NOT NULL,
  cosec INTEGER NOT NULL,
  fund INTEGER NOT NULL,
  operations INTEGER NOT NULL,
  corpfinance INTEGER NOT NULL,
  investment INTEGER NOT NULL,
  body TEXT NOT NULL,
  title TEXT NOT NULL,  
  FOREIGN KEY (author_id) REFERENCES user (id)
  
  
);
